added-tests-for-book-and-category
margosalii/online-book-store pull request #14
Opened 2024-08-20 17:27 UTC by margosalii

2024-08-20 17:34 UTC, margosalii commented
![Без имени](https://github.com/user-attachments/assets/50bb9617-df48-4088-a701-a4a4155dad7f)

2024-08-22 09:17 UTC, MentorMateAcademy requested changes

2024-08-22 09:17 UTC, MentorMateAcademy commented on src/test/java/mate/academy/store/controller/BookControllerTest.java
> +    protected static MockMvc mockMvc;
Why protected?

2024-08-22 09:17 UTC, MentorMateAcademy commented on src/test/java/mate/academy/store/controller/BookControllerTest.java
> +                .setPrice(BigDecimal.valueOf(8)).setCategoryIds(Collections.emptySet()));
write in stack form

2024-08-22 09:17 UTC, MentorMateAcademy commented on src/test/java/mate/academy/store/controller/BookControllerTest.java
> +        Assertions.assertEquals(expected, Arrays.stream(actual).toList());
you don`t need stream, Arrays.asList

2024-08-22 09:17 UTC, MentorMateAcademy commented on src/test/java/mate/academy/store/controller/BookControllerTest.java
> +        requestDto.setIsbn("9780141321002");
if you use same strings just save it to constants

2024-08-22 09:17 UTC, MentorMateAcademy commented on src/test/java/mate/academy/store/controller/CategoryControllerTest.java
> +                put("/categories/1")
constants

2024-08-22 09:17 UTC, MentorMateAcademy commented on src/test/java/mate/academy/store/service/book/BookServiceTest.java
> +    private BookServiceImpl bookService;
inject place after mocks

2024-08-22 12:47 UTC, merged