tests-for-shopping-cart
margosalii/online-book-store pull request #15
Opened 2024-08-27 09:24 UTC by margosalii

2024-08-28 09:28 UTC, margosalii commented
![1](https://github.com/user-attachments/assets/f1b16c76-2be3-43b0-a51b-570d6ee76e42)

2024-08-28 12:59 UTC, Elena-Bruyako requested changes
good job!

2024-08-28 12:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/store/model/ShoppingCart.java
> +@EqualsAndHashCode
If you add these annotation, you need to exclude cartItems
@EqualsAndHashCode.Exclude

2024-08-28 12:59 UTC, Elena-Bruyako commented on src/test/java/mate/academy/store/controller/ShoppingCartControllerTest.java
> +        Assertions.assertEquals(expected, actual);
use static imports

2024-08-28 12:59 UTC, Elena-Bruyako commented on src/test/java/mate/academy/store/controller/ShoppingCartControllerTest.java
> +    }
check if you need not valid test cases (not valid id for example)

2024-08-28 21:01 UTC, margosalii commented on src/test/java/mate/academy/store/controller/ShoppingCartControllerTest.java
> +    }
> check if you need not valid test cases (not valid id for example)

i tried something like that, but i don't know how to fix that problem
![image](https://github.com/user-attachments/assets/1b58ca7e-0be7-409c-81af-6f211b9f3dde)

2024-08-29 18:27 UTC, okuzan approved these changes

2024-08-29 18:27 UTC, okuzan commented on src/test/java/mate/academy/store/controller/ShoppingCartControllerTest.java
> +    )
extract scripts common to each test of class to the class level

2024-08-29 18:27 UTC, okuzan commented on src/test/resources/database/cart.items/add-cart-item.sql
> +insert into cart_items (id, shopping_cart_id, book_id, quantity) values (1, 1, 1, 2);
![image](https://github.com/user-attachments/assets/bcf32035-8751-434f-960c-a6e98d372538)
minor issue but when you see red signs, add an empty line at EOF

2024-08-29 18:27 UTC, okuzan commented on src/test/java/mate/academy/store/service/shopping/cart/ShoppingCartServiceTest.java
> +
```suggestion
```

2024-08-30 08:28 UTC, merged