data-jpa-and-liquibase-are-used
margosalii/online-book-store pull request #3
Opened 2024-07-09 18:20 UTC by margosalii

2024-07-10 11:31 UTC, MentorMateAcademy requested changes

2024-07-10 11:31 UTC, MentorMateAcademy commented on src/main/java/mate/academy/store/service/impl/BookServiceImpl.java
> +    public void updateById(Long id, CreateBookRequestDto requestDto) {
guess you should return entity instead of void

2024-07-10 17:49 UTC, Elena-Bruyako requested changes
only one comment

2024-07-10 17:49 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  name: coverImage
```suggestion
                  name: cover_image
```

2024-07-11 14:49 UTC, MAMentorFX approved these changes

2024-07-11 16:18 UTC, merged