added-GlobalExceptionHandler-and-data-validation
margosalii/online-book-store pull request #5
Opened 2024-07-15 16:50 UTC by margosalii

2024-07-16 07:26 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-16 07:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/store/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

check other String

2024-07-16 07:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/store/controller/BookController.java
> +    public BookDto updateBook(@PathVariable Long id,
```suggestion
    public BookDto updateBook(@PathVariable @Positive Long id,
```

Add `@Validated` under the controller
Also, check other PathVariable

2024-07-16 07:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/store/controller/BookController.java
> +                              @RequestBody @Valid CreateBookRequestDto requestDto) {
Add `@Valid` to search(BookSearchParameters searchParameters)

2024-07-17 10:04 UTC, MentorMateAcademy requested changes

2024-07-17 10:04 UTC, MentorMateAcademy commented on src/main/java/mate/academy/store/dto/CreateBookRequestDto.java
> +    @Min(0)
better use @Positive

2024-07-17 10:04 UTC, MentorMateAcademy commented on src/main/java/mate/academy/store/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
save strings to constants

2024-07-17 10:04 UTC, MentorMateAcademy commented on src/main/java/mate/academy/store/exception/CustomGlobalExceptionHandler.java
> +            String field = ((FieldError) objectError).getField();
```suggestion
        if (objectError instanceof FieldError fieldError) {
            String field = fieldError.getField();
```

2024-07-17 10:04 UTC, MentorMateAcademy commented on src/main/java/mate/academy/store/dto/CreateBookRequestDto.java
>      private String description;
You can validate descriptions

2024-07-17 11:44 UTC, Elena-Bruyako approved these changes

2024-07-17 12:06 UTC, merged